#!/bin/bash
make clean
#
#  buildable platforms of Marcelino cores
make marcelino_328_8
make marcelino_328_16
make marcelino_328p_8
make marcelino_328p_16
make marcelino_168_8
make marcelino_168_16

avr-gcc -Os -mmcu=attiny85 -DF_CPU=8000000UL attiny85_8MHz.c -o attiny85_8MHz.elf
avr-objcopy -O ihex attiny85_8MHz.elf attiny85_8MHz.hex
rm attiny85_8MHz.elf
avr-gcc -Os -mmcu=attiny85 -DF_CPU=1000000UL attiny85_1MHz.c -o attiny85_1MHz.elf
avr-objcopy -O ihex attiny85_1MHz.elf attiny85_1MHz.hex
rm attiny85_1MHz.elf
