#!/bin/bash
make clean
#
#  buildable platforms of somewhat questionable support level
make lilypad
make pro8
make pro16
make pro20
make atmega328_pro8
make sanguino
make mega1280
make luminet
make diecimila
make bobuino
make wildfirev2
make atmega1284
make atmega32
make atmega88
make atmega168p

#
# The "big three" standard bootloaders.
# These need to be built AFTER the platforms, or they'll get renamed
make atmega8
make atmega168
make atmega328

#for marcelino boards

make marcelino_328_8
make marcelino_328_16
make marcelino_328p_8
make marcelino_328p_16
make marcelino_168_8
make marcelino_168_16

avr-gcc -Os -mmcu=attiny85 -DF_CPU=8000000UL attiny85_8MHz.c -o attiny85_8MHz.elf
avr-objcopy -O ihex attiny85_8MHz.elf attiny85_8MHz.hex
rm attiny85_8MHz.elf
avr-gcc -Os -mmcu=attiny85 -DF_CPU=1000000UL attiny85_1MHz.c -o attiny85_1MHz.elf
avr-objcopy -O ihex attiny85_1MHz.elf attiny85_1MHz.hex
rm attiny85_1MHz.elf
